global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pi5-supernode'
    replica: 'primary'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Pi5 Supernode services
  - job_name: 'pi5-supernode-services'
    static_configs:
      - targets: 
        - 'api-gateway:3000'
        - 'network-service:3001'
        - 'vpn-service:3002'
        - 'automation-service:3003'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics
  - job_name: 'pi5-system'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Application-specific metrics
  - job_name: 'pi5-application-metrics'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 60s