import { 
  Wifi, Power, RefreshCw, Server, Settings as Gear, Shield, Globe, HelpCircle,
  Bell, FileText, Cloud, Terminal, Download, BarChart3, Webhook, MessageCircle,
  Zap, Users, Activity, Database, Archive, Key, Edit, Trash2, Plus,
  Router, Network, Smartphone, Monitor, Home, Gamepad2, Camera, Brain,
  LayoutDashboard, HardDrive, Menu, X, Search, Scan, UserX, 
  TrendingUp, TrendingDown, Minus, MoreHorizontal, Cpu, MemoryStick, Gauge,
  User, Lock, Share2, Usb, Copy, Check, ExternalLink, Bug,
  MousePointer, Send, Clock, TestTube, GitBranch, Heart, Package
} from 'lucide-react';

export const ICONS: Record<string, React.ComponentType<any>> = {
  wifi: Wifi,
  power: Power,
  refresh: RefreshCw,
  refreshcw: RefreshCw,
  server: Server,
  settings: Gear,
  gear: Gear,
  shield: Shield,
  globe: Globe,
  bell: Bell,
  filetext: FileText,
  cloud: Cloud,
  terminal: Terminal,
  download: Download,
  barchart3: BarChart3,
  webhook: Webhook,
  messagecircle: MessageCircle,
  zap: Zap,
  users: Users,
  activity: Activity,
  database: Database,
  archive: Archive,
  key: Key,
  edit: Edit,
  trash2: Trash2,
  plus: Plus,
  router: Router,
  network: Network,
  smartphone: Smartphone,
  monitor: Monitor,
  home: Home,
  gamepad2: Gamepad2,
  camera: Camera,
  brain: Brain,
  layoutdashboard: LayoutDashboard,
  harddrive: HardDrive,
  menu: Menu,
  x: X,
  search: Search,
  scan: Scan,
  userx: UserX,
  trendingup: TrendingUp,
  trendingdown: TrendingDown,
  minus: Minus,
  morehorizontal: MoreHorizontal,
  cpu: Cpu,
  memorystick: MemoryStick,
  gauge: Gauge,
  user: User,
  lock: Lock,
  share2: Share2,
  usb: Usb,
  copy: Copy,
  check: Check,
  externallink: ExternalLink,
  bug: Bug,
  mousepointer: MousePointer,
  send: Send,
  clock: Clock,
  testtube: TestTube,
  gitbranch: GitBranch,
  heart: Heart,
  package: Package
};

export const getIcon = (name?: string): React.ComponentType<any> => {
  if (!name) return HelpCircle;
  const key = name.toLowerCase().replace(/[-_]/g, '');
  return ICONS[key] ?? HelpCircle;
};